# Generated by Django 4.2.1 on 2023-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csvv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
